[package]
name = "soroban-test-wasms"
version.workspace = true
description = "crate full of precompiled test WASM binaries for soroban -- for use in other tests, do not publish"
edition = "2021"
publish = false
rust-version.workspace = true
