[package]
name = "soroban-synth-wasm"
description = "Utilities for synthesizing soroban contract wasm modules."
homepage = "https://github.com/stellar/rs-soroban-env"
repository = "https://github.com/stellar/rs-soroban-env"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
version.workspace = true
edition = "2021"
rust-version = "1.69"
publish = false

[dependencies]
wasm-encoder = "0.18.0"
wasmparser = "0.92.0"
soroban-env-common = { workspace = true }

[dev-dependencies]
expect-test = "1.4.0"
wasmprinter = "0.2.41"
