[package]
name = "soroban-env-common"
description = "Soroban contract environment common types and functionality."
homepage = "https://github.com/stellar/rs-soroban-env"
repository = "https://github.com/stellar/rs-soroban-env"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
version = "0.0.5"
readme = "../README.md"
edition = "2021"
rust-version = "1.63"

[dependencies]
soroban-env-macros = { version = "0.0.5" }
stellar-xdr = { version = "0.0.2", default-features = false, features = [ "next" ] }
wasmi = { package = "soroban-wasmi", version = "0.11.0", optional = true }
static_assertions = "1.1.0"

[features]
std = ["stellar-xdr/std", "stellar-xdr/base64"]
serde = ["stellar-xdr/serde"]
vm = ["wasmi"]

[package.metadata.docs.rs]
all-features = true
